"""recommend_placement -- specimen placement scorer and verification-grid emitter (MOT-04.3).

console_script: `ros2 run crackvision_motion recommend_placement`. Runs under the system python3
(ROS Humble, py3.10), never `./env.sh` -- invoked via `scripts/ros/env_ros.sh`. See
`docs/INTERFACES.md` §7.4 for the CLI contract and exit codes, and §7.3 for the output schema.
"""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path
from typing import Any, Dict, Optional

import yaml

from .cli_common import PreconditionError, find_root, run_cli
from .placement import recommend, verification_config, view_verification_config
from .reachability_core import ConfigError, config_sha256, load_config
from .reachability_map import PlacementError, load_map, load_placement, validate_placement

TOOL = "recommend_placement"

DEFAULT_MAP = "data/motion/reachability_map.json"
DEFAULT_CONFIG = "config/motion/reachability.yaml"
DEFAULT_OUT = "config/motion/specimen_placement.yaml"
DEFAULT_LIMITS = "config/robot/b601_dm_limits.yaml"

_HEADER = (
    "# Generated by recommend_placement (MOT-04.3). This is a NOMINAL recommendation, not a\n"
    "# measurement: the operator places the specimen at placement.center_xy_m/yaw_rad, and\n"
    "# MOT-10 measures the real, as-placed pose, which supersedes this file for every\n"
    "# downstream consumer. Do not hand-edit; re-run recommend_placement instead.\n"
)


def _resolve(root: Path, value: Optional[Path], default: str) -> Path:
    if value is not None:
        return Path(value).expanduser().resolve()
    return (root / default).resolve()


def _sha256_of(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _assert_grid_consistency(map_dict: dict, cfg: dict) -> None:
    """The map and the config must share the same x/y sweep resolution (§7.4): `placement.
    tolerance_m` is interpreted against the map's own grid step, and `verification_config` halves
    it, so a config authored at a different step would silently mis-size both."""
    map_grid = map_dict["grid"]["grid"]
    for axis in ("x_m", "y_m"):
        map_step = float(map_grid[axis]["step"])
        cfg_step = float(cfg["grid"][axis]["step"])
        if abs(map_step - cfg_step) > 1e-9:
            raise ConfigError(
                f"reachability config grid.{axis}.step ({cfg_step}) does not match the map's "
                f"grid.{axis}.step ({map_step}); recommend_placement requires the same sweep "
                "resolution in both"
            )


def _write_yaml(path: Path, header: str, payload: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    path.write_text(header + body, encoding="utf-8")


def _load_placement_or_raise(path: Path) -> None:
    try:
        load_placement(path)
    except OSError as exc:
        raise PlacementError(f"could not read placement file {path}: {exc}") from exc


def _extra_args(parser) -> None:
    parser.add_argument("--map", type=Path, default=None, help="reachability map JSON (default: data/motion/reachability_map.json)")
    parser.add_argument("--reachability-config", type=Path, default=None, help="reachability config YAML (default: config/motion/reachability.yaml)")
    parser.add_argument("--out", type=Path, default=None, help="specimen placement YAML to write (default: config/motion/specimen_placement.yaml)")
    parser.add_argument("--emit-verify-config", type=Path, default=None, help="also write a half-step verification-grid reachability config here")
    parser.add_argument("--emit-view-config", type=Path, default=None, help="also write a wrist-camera view check config (camera_link above the placement centre, ADR-014) here")
    parser.add_argument("--validate-placement", type=Path, default=None, help="validate-only: check PATH against the schema and exit (0 valid, 2 invalid)")


def _run(args, log, summary) -> Dict[str, Any]:
    root = Path(args.root).expanduser().resolve() if args.root is not None else find_root()

    if args.validate_placement is not None:
        validate_path = Path(args.validate_placement).expanduser().resolve()
        _load_placement_or_raise(validate_path)
        log.info("valid specimen placement: %s", validate_path)
        summary.increment("validated")
        return {"status": "ok"}

    map_path = _resolve(root, args.map, DEFAULT_MAP)
    config_path = _resolve(root, args.reachability_config, DEFAULT_CONFIG)
    out_path = _resolve(root, args.out, DEFAULT_OUT)
    limits_path = root / DEFAULT_LIMITS

    if args.skip_existing and out_path.exists():
        log.info("--skip-existing: %s already exists, skipping", out_path)
        summary.increment("skipped")
        return {"status": "ok"}

    if not map_path.is_file():
        raise PreconditionError(f"reachability map not found: {map_path}")

    map_dict = load_map(map_path, limits_path=limits_path)
    if not map_dict.get("complete", False):
        raise PreconditionError(f"reachability map {map_path} is incomplete (complete: false)")

    cfg = load_config(config_path)
    _assert_grid_consistency(map_dict, cfg)

    map_sha = _sha256_of(map_path)
    cfg_sha = config_sha256(config_path)

    placement_dict = recommend(map_dict, cfg, map_sha, cfg_sha)
    validate_placement(placement_dict)
    _write_yaml(out_path, _HEADER, placement_dict)
    log.info("wrote specimen placement to %s (feasible=%s)", out_path, placement_dict["feasible"])
    summary.increment("feasible" if placement_dict["feasible"] else "infeasible")

    if args.emit_verify_config is not None:
        if not placement_dict["feasible"]:
            log.warning("no feasible placement: skipping --emit-verify-config")
        else:
            verify_path = Path(args.emit_verify_config).expanduser().resolve()
            verify_cfg = verification_config(placement_dict["placement"], cfg)
            verify_path.parent.mkdir(parents=True, exist_ok=True)
            verify_path.write_text(
                yaml.safe_dump(verify_cfg, sort_keys=False, default_flow_style=False), encoding="utf-8"
            )
            load_config(verify_path)  # self-check: must itself be a valid reachability_config/1
            log.info("wrote verification-grid config to %s", verify_path)
            summary.increment("verify_config_written")

    if args.emit_view_config is not None:
        if not placement_dict["feasible"]:
            log.warning("no feasible placement: skipping --emit-view-config")
        else:
            view_path = Path(args.emit_view_config).expanduser().resolve()
            view_cfg = view_verification_config(placement_dict["placement"], cfg)
            view_path.parent.mkdir(parents=True, exist_ok=True)
            view_path.write_text(yaml.safe_dump(view_cfg, sort_keys=False, default_flow_style=False), encoding="utf-8")
            load_config(view_path)  # self-check
            log.info("wrote camera view-check config to %s", view_path)
            summary.increment("view_config_written")

    if not placement_dict["feasible"]:
        return {"status": "failed"}
    return {"status": "ok"}


def main(argv=None) -> int:
    return run_cli(TOOL, _run, argv if argv is not None else sys.argv[1:], extra_args=_extra_args)


if __name__ == "__main__":
    sys.exit(main())
