"""survey_to_scene -- validated `crackvision.workcell_survey/1` record -> measured
`crackvision.scene_config/1` file, plus verification-grid emitters and a drift check (MOT-10.3).

console_script: `ros2 run crackvision_motion survey_to_scene`. Runs under the system python3
(ROS Humble, py3.10), never `./env.sh` -- invoked via `scripts/ros/env_ros.sh`, like every other
tool in this package. Stdlib + PyYAML only (via `survey_core`/`scene_core`/`reachability_core`/
`placement`) -- no rclpy import anywhere in this file, so it is importable and testable without a
colcon build; it never touches an action server or `/move_action` (file-in/file-out only). See
`docs/motion/WORKCELL_SURVEY.md` for the operator procedure this tool's input comes from,
`docs/INTERFACES.md` §12 for the survey schema/derivation rules, and `docs/motion/SCENE.md` for
the measured-scene workflow this tool completes.

Modes (mutually exclusive):
    --validate-survey PATH   validate PATH against crackvision.workcell_survey/1 and exit
                              (0 valid, 2 invalid); every other flag is ignored.
    --survey PATH --out PATH convert: derive measured scene objects from PATH and write a
                              crackvision.scene_config/1 file to --out. Optionally also
                              --emit-verify-config/--emit-view-config a placement/view
                              reachability-check config centred on the measured specimen pose.
    --survey PATH --check-scene PATH
                              regenerate from --survey and byte-compare against the committed
                              scene file at --check-scene (0 identical, 1 drift -- a unified diff
                              is logged). Writes nothing.

There is deliberately no default for --out: this tool never overwrites `config/scene/scene.yaml`
unless that exact path is given explicitly as --out.
"""

from __future__ import annotations

import difflib
import sys
from pathlib import Path
from typing import Any, Dict, Optional, Tuple

import yaml

from .cli_common import PreconditionError, find_root, run_cli
from .placement import verification_config, view_verification_config
from .reachability_core import ConfigError, load_config as load_reachability_config
from .scene_core import SCHEMA_ID as SCENE_SCHEMA_ID, load_config as load_scene_config
from .survey_core import SurveyError, derive_scene, load_survey, survey_sha256

TOOL = "survey_to_scene"

DEFAULT_REACHABILITY_CONFIG = "config/motion/reachability.yaml"
GENERATOR = "survey_to_scene (MOT-10.3)"
SCENE_FRAME = "base_link"  # §12.1: every survey-derived pose is already expressed in base_link


def _resolve(root: Path, value: Optional[Path], default: str) -> Path:
    if value is not None:
        return Path(value).expanduser().resolve()
    return (root / default).resolve()


def _survey_label(root: Path, survey_path: Path) -> str:
    """Repo-relative path when possible (keeps the header portable across machines), else the
    absolute path. Must be a pure function of (root, survey_path) for --check-scene to be
    byte-comparable against a --out regenerated from the same inputs."""
    try:
        return str(survey_path.relative_to(root))
    except ValueError:
        return str(survey_path)


def _header(survey_label: str, survey_sha: str) -> str:
    return (
        f"# Generated by {GENERATOR} from survey {survey_label} (sha256={survey_sha}).\n"
        "# Do not hand-edit this file -- re-run survey_to_scene from the same survey instead.\n"
    )


def _build_scene(root: Path, survey_path: Path) -> Tuple[bytes, Dict[str, Any]]:
    """Load + derive the survey at `survey_path` and render the deterministic scene.yaml bytes.
    Returns (bytes, derive_scene's full result) -- the caller needs `derived['derived']` to build
    the verify/view configs from the measured specimen pose without re-deriving it."""
    try:
        survey = load_survey(survey_path)
        survey_sha = survey_sha256(survey_path)
        derived = derive_scene(survey, survey_sha)
    except SurveyError as exc:
        raise ConfigError(str(exc)) from exc

    scene_dict = {
        "schema": SCENE_SCHEMA_ID,
        "frame": SCENE_FRAME,
        "objects": derived["objects"],
        "allowed_collisions": derived["allowed_collisions"],
    }
    body = yaml.safe_dump(scene_dict, sort_keys=False, default_flow_style=False)
    header = _header(_survey_label(root, survey_path), survey_sha)
    return (header + body).encode("utf-8"), derived


def _specimen_placement_dict(derived: Dict[str, Any], cfg: Dict[str, Any]) -> Dict[str, Any]:
    """Placement-shaped input for `placement.verification_config`/`view_verification_config`,
    built from the MEASURED specimen pose (center/yaw/footprint/top-z, §12.7 rule 1/2) --
    `tolerance_m` and `standoffs_m` are not survey quantities (§12 says nothing about them), so
    they are taken from `cfg` (`config/motion/reachability.yaml`'s own `placement.tolerance_m` and
    `grid.standoffs_m`), the same fields MOT-04.3 already uses for this exact purpose."""
    specimen = derived["derived"]["specimen"]
    return {
        "center_xy_m": list(specimen["centre_m"]),
        "yaw_rad": specimen["yaw_rad"],
        "footprint_m": list(specimen["footprint_m"]),
        "tolerance_m": cfg["placement"]["tolerance_m"],
        "surface_z_m": specimen["top_z_m"],
        "standoffs_m": list(cfg["grid"]["standoffs_m"]),
    }


def _extra_args(parser) -> None:
    parser.add_argument(
        "--survey", type=Path, default=None,
        help="crackvision.workcell_survey/1 YAML to read (required unless --validate-survey)",
    )
    parser.add_argument(
        "--out", type=Path, default=None,
        help="measured scene.yaml to write (no default -- never config/scene/scene.yaml unless given explicitly)",
    )
    parser.add_argument(
        "--validate-survey", type=Path, default=None,
        help="validate-only: check PATH against crackvision.workcell_survey/1 and exit (0 valid, 2 invalid)",
    )
    parser.add_argument(
        "--check-scene", type=Path, default=None,
        help="regenerate from --survey and diff against this committed scene.yaml (0 identical, 1 drift); writes nothing",
    )
    parser.add_argument(
        "--emit-verify-config", type=Path, default=None,
        help="also write a half-step placement verification reachability config centred on the measured specimen pose",
    )
    parser.add_argument(
        "--emit-view-config", type=Path, default=None,
        help="also write a wrist-camera view-check reachability config centred on the measured specimen pose",
    )
    parser.add_argument(
        "--reachability-config", type=Path, default=None,
        help="reachability config YAML backing --emit-verify-config/--emit-view-config (default: config/motion/reachability.yaml)",
    )


def _run(args, log, summary) -> Dict[str, Any]:
    root = Path(args.root).expanduser().resolve() if args.root is not None else find_root()

    if args.validate_survey is not None:
        validate_path = Path(args.validate_survey).expanduser().resolve()
        if not validate_path.is_file():
            raise PreconditionError(f"survey file not found: {validate_path}")
        try:
            load_survey(validate_path)
        except SurveyError as exc:
            raise ConfigError(str(exc)) from exc
        log.info("valid workcell survey: %s", validate_path)
        summary.increment("validated")
        return {"status": "ok"}

    if args.check_scene is not None and args.out is not None:
        raise ConfigError("--check-scene and --out are mutually exclusive: check or write, not both")

    if args.survey is None:
        raise ConfigError("--survey is required unless --validate-survey is given")
    survey_path = Path(args.survey).expanduser().resolve()
    if not survey_path.is_file():
        raise PreconditionError(f"survey file not found: {survey_path}")

    if args.check_scene is not None:
        check_path = Path(args.check_scene).expanduser().resolve()
        if not check_path.is_file():
            raise PreconditionError(f"scene file not found: {check_path}")
        regenerated, _derived = _build_scene(root, survey_path)
        committed = check_path.read_bytes()
        if regenerated == committed:
            log.info("%s matches a fresh regeneration from %s: no drift", check_path, survey_path)
            summary.increment("identical")
            return {"status": "ok"}
        diff = "".join(difflib.unified_diff(
            committed.decode("utf-8", errors="replace").splitlines(keepends=True),
            regenerated.decode("utf-8", errors="replace").splitlines(keepends=True),
            fromfile=str(check_path),
            tofile=f"regenerated from {survey_path}",
        ))
        log.error(
            "scene drift detected: %s no longer matches a fresh regeneration from %s\n%s",
            check_path, survey_path, diff,
        )
        summary.add_error(f"scene drift detected between {check_path} and {survey_path}")
        summary.increment("drifted")
        return {"status": "failed"}

    if args.out is None:
        raise ConfigError("--out is required for conversion (or use --validate-survey / --check-scene)")
    out_path = Path(args.out).expanduser().resolve()

    if args.skip_existing and out_path.exists():
        log.info("--skip-existing: %s already exists, skipping", out_path)
        summary.increment("skipped")
        return {"status": "ok"}

    scene_bytes, derived = _build_scene(root, survey_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_bytes(scene_bytes)
    load_scene_config(out_path)  # self-check: must itself be a valid crackvision.scene_config/1
    log.info("wrote measured scene to %s", out_path)
    summary.increment("written")

    if args.emit_verify_config is not None or args.emit_view_config is not None:
        reachability_path = _resolve(root, args.reachability_config, DEFAULT_REACHABILITY_CONFIG)
        cfg = load_reachability_config(reachability_path)
        placement = _specimen_placement_dict(derived, cfg)

        if args.emit_verify_config is not None:
            verify_path = Path(args.emit_verify_config).expanduser().resolve()
            verify_cfg = verification_config(placement, cfg)
            verify_path.parent.mkdir(parents=True, exist_ok=True)
            verify_path.write_text(
                yaml.safe_dump(verify_cfg, sort_keys=False, default_flow_style=False), encoding="utf-8"
            )
            load_reachability_config(verify_path)  # self-check
            log.info("wrote placement verification config to %s", verify_path)
            summary.increment("verify_config_written")

        if args.emit_view_config is not None:
            view_path = Path(args.emit_view_config).expanduser().resolve()
            view_cfg = view_verification_config(placement, cfg)
            view_path.parent.mkdir(parents=True, exist_ok=True)
            view_path.write_text(
                yaml.safe_dump(view_cfg, sort_keys=False, default_flow_style=False), encoding="utf-8"
            )
            load_reachability_config(view_path)  # self-check
            log.info("wrote view verification config to %s", view_path)
            summary.increment("view_config_written")

    return {"status": "ok"}


def main(argv=None) -> int:
    return run_cli(TOOL, _run, argv if argv is not None else sys.argv[1:], extra_args=_extra_args)


if __name__ == "__main__":
    sys.exit(main())
